
services:
  mysql:
    image: mysql:8.0
    container_name: cinego-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinego
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
